apiVersion: v1
kind: ConfigMap
metadata:
  name: aegis-config
  namespace: aegis-ai
data:
  AEGIS_ENV: production
  AEGIS_STORAGE_BACKEND: minio
  AEGIS_MINIO_ENDPOINT: minio:9000
  AEGIS_MLFLOW_TRACKING_URI: http://mlflow:5000
  AEGIS_OLLAMA_URL: http://ollama:11434
  AEGIS_QDRANT_URL: http://qdrant:6333
  AEGIS_REDIS_URL: redis://redis:6379/0
